### ISSUE TITLE
请问 Position Embedding 可以被训练吗？

### ISSUE THREAD

**Issue by ZJUguquan** [bojone/attention#1]
@bojone 您好，看了您的代码（Keras），很赞！
请教个问题：
在输入经过 Word Embedding 之后，又经过了一层 `Position Embedding`，这相当于补充了词向量的位置信息。
但由于Keras的Layer中的权值矩阵是默认是可以被训练的（trainable），那么补充的 `Position Embedding` 的参数信息也会在BP中不断被优化，这样的话增加 `Position Embedding` 这一层并计算`sin`和`cos`值只是相当于对 PE 的权值做了一次初始化？随着迭代进行，其权值也会不断变化。。。
还是说在调用`Position Embedding`的时候应该要设定`trainable=False`呢?

希望得到您的解答！感谢~！

**Comment by bojone** [comment]
目前的写法是不会被训练的，不管trainable=False还是trainable=True都不会，因为目前只是按照公式算出来的Position Embedding

**Comment by bojone** [comment]
Keras中可训练的权重一般要add_weight来添加，但Position Embedding层并没有。你可以对比Position Embedding层和Attention层的实现，就知道区别在哪了。

**Comment by ZJUguquan** [comment]
的确，Position Embedding层只依赖序列中的词的位置（pos）和embedding维度（size）
Got it！Thanks~
