### ISSUE TITLE
请问一下，tf版的78，80行的转置操作是什么意思呢？ 去掉这两行进行训练对结果也没什么影响。

### ISSUE THREAD

**Issue by yangjun023** [bojone/attention#12]
请问一下，tf版的78，80行的转置操作是什么意思呢？ 去掉这两行进行训练对结果也没什么影响。

**Comment by yangjun023** [comment]
又想了一下，转置是为了和长度保持一致从而进行mask，如果去掉转置就不是对长度进行mask了，就变得没有什么物理意义了，虽然运行也不会报错。
感觉神经网络内部即使什么矩阵操作写错了也没问题，也能从另外一个角度进行训练。楼主认为呢？

**Comment by bojone** [comment]
https://kexue.fm/archives/4765/comment-page-5#comment-10520
