### ISSUE TITLE
Position_Embedding肯能有些问题

### ISSUE THREAD

**Issue by liangoy** [bojone/attention#2]
Position_Embedding中
position_ij = tf.concat([tf.cos(position_ij), tf.sin(position_ij)], 1)
只能将cos和sin前后连接,并不能做到论文中的交叉连接

我认为应该把这行代码替换成:
    cos = tf.expand_dims(tf.cos(position_ij), 2)
    sin = tf.expand_dims(tf.sin(position_ij), 2)
    position_ij = tf.concat([cos, sin], 2)
    position_ij = tf.reshape(position_ij, shape=[seq_len, -1])

不知道这样对不对,如果不对请指正

**Comment by bojone** [comment]
你这样改也可以，严格按照论文来做。但我认为是没区别的。

假如你的Position_Embedding是拼接到原来的词向量中，那么将cos和sin前后连接还是交叉连接，都是没区别的，因为你下一步都是接一个变换矩阵而已；

如果你的Position_Embedding是加到原来的词向量中，那么两种方式貌似是有点区别的，但是要注意的是，词向量本身没有局部结构，也就是说，50维的词向量，将每一维打乱重新排个序（当然整体要按同样的顺序来重新排序），它还是等价于原来的词向量。既然相加的对象（词向量）都没有局部结构，我们也没必要强调被加的对象（Position_Embedding）的局部结构（也就是交叉连接）了。

事实上，这也是我对把Position_Embedding加到原来的词向量中这种组合方式存疑的原因之一。
