### ISSUE TITLE
K.permute_dimensions(A, (0,3,2,1))运行时报错

### ISSUE THREAD

**Issue by njuccq** [bojone/attention#3]
您好，我在运行您的代码时，出现了错误，在
#计算内积，然后mask，然后softmax
A = K.batch_dot(Q_seq, K_seq, axes=[3,3])
 A = K.permute_dimensions(A, (0,3,2,1))
这一块，报了valueError:('You cannot drop a non-broadcastable dimension.'((False,False,False,False,False),(0,3,2,1)
这是因为batch_dot的计算结果是5维，而permute_dimension中参数是4维吗？我的输入格式跟你的是一样的，想请教你这个问题要怎么解决？

**Comment by bojone** [comment]
我不大清楚你的输入情况。
正常的输入Q_seq、K_seq、V_seq都应该是3维的（包括batch_size这一维）。

**Comment by kisxin** [comment]
我也碰到这个问题了，请问你解决了没有？

**Comment by bojone** [comment]
你是不是theano后端？目前还有这么多人用theano后端么？

**Comment by bojone** [comment]
@njuccq @kisxin

**Comment by Lauzanhing** [comment]
@bojone 
我用theano作为后端的时候也遇到了相同的问题  计算出来的结果是5D的。
当我用tensorflow1.7作为后端的时候出现了如下错误：
InvalidArgumentError (see above for traceback): indices[16,69] = 20978 is not in [0, 20000)
	 [[Node: embedding_1/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1/embeddings/read, _arg_input_1_0_3)]]

想要问一下您所用的keras和tensorflow版本

**Comment by Lauzanhing** [comment]
@bojone 
我用theano作为后端的时候也遇到了相同的问题  计算出来的结果是5D的。
当我用tensorflow1.7作为后端的时候出现了如下错误：
InvalidArgumentError (see above for traceback): indices[16,69] = 20978 is not in [0, 20000)
	 [[Node: embedding_1/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1/embeddings/read, _arg_input_1_0_3)]]

想要问一下您所用的keras和tensorflow版本

**Comment by guofengjpggwk** [comment]
我这应该也是同样的错误：
encoder_input = Input(shape=(90,), dtype='int32')

x_mask = Lambda(lambda x: K.cast(K.greater(K.expand_dims(x, 2), 0), 'int32')）(encoder_input)

embedded_sequences = Embedding(length,output_dim=512,input_length=90）(encoder_input)

encoder_inputs = 
Attention(8, 16)([embedded_sequences,embedded_sequences,embedded_sequences, x_mask, x_mask])
报错：
  File "D:\Anaconda\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)

  File "<ipython-input-3-2752b128815e>", line 59, in call
    A = K.permute_dimensions(A, (0,3,2,1))
……
ValueError: Dimension must be 5 but is 4 for 'attention_1/transpose_7' (op: 'Transpose') with input shapes: [?,?,?,?,8], [4].

**Comment by bojone** [comment]
@guofengjpggwk 你这个完全是乱来... Attention的后两个参数，是seq_len！！是(batch_size, 1)的形状，你从我另外一个代码抄来的x_mask生搬硬套干嘛...

**Comment by guofengjpggwk** [comment]
哦，懂了，我把x_mask = Lambda(lambda x: K.cast(K.greater(K.expand_dims(x, 2), 0), 'int32')）(encoder_input)改成encoder_len = Input(shape=(1,), dtype='int32')，成功运行了

**Comment by fareise** [comment]
您好，我也报了同样的错误，我再自己的服务器上运行是正常的，但是用kaggle的kernel运行就会报这个错误，后端是tensorflow的，请问一下怎么解决

**Comment by fareise** [comment]
报错：ValueError: Dimension must be 5 but is 4 for 'attention_5/transpose_8' (op: 'Transpose') with input shapes: [?,8,?,8,?], [4].

**Comment by ReapersScythe** [comment]
> 报错：ValueError: Dimension must be 5 but is 4 for 'attention_5/transpose_8' (op: 'Transpose') with input shapes: [?,8,?,8,?], [4].

我也在kaggle上报了同样的错误，
A = K.batch_dot(Q_seq, K_seq, axes=[3,3]) / self.size_per_head**0.5 点积后得到的张量shape = (?,8,?,8,?)
Reshape为原四维张量后可以运行

**Comment by myndtt** [comment]
好像跟tensorflow版本相关，之前跑的好好地，换了一个版本就也报这样的错(忘了之前的版本)

**Comment by liuchenbaidu** [comment]
有人修复了这个与版本有关的错误了吗？

**Comment by bojone** [comment]
本项目不再跟进新版本的keras/tf。
如果有新版本的需求，可以到 https://github.com/bojone/bert4keras/blob/master/bert4keras/layers.py 复制对应的函数。
