### ISSUE TITLE
position_ij = tf.concat([tf.cos(position_ij), tf.sin(position_ij)], 1) 

### ISSUE THREAD

**Issue by imhuay** [bojone/attention#5]
原文分的是奇偶，这里这么处理好像不对

**Comment by jsksxs360** [comment]
Position Embedding 中我觉得元素打乱顺序应该没什么关系，作者的代码中将经过 cos 的 sin 的数值分别放在一起应该如果是 concat 模式的话感觉对结果是没什么影响，如果是 sum 的话就不好说了。

PS: 这个层好像写的有点问题，实际运行时，在训练集上达到一定的准确率后就上不去了，永远训练不出来（不会过拟合）。
